#!/usr/bin/env python3
"""Record what GreynirCorrect currently reports for the development corpus.

The output is a review aid for humans, not a test fixture. After a dependency
upgrade, a diff in ``corpus/observed.json`` shows exactly what changed upstream
— which is far easier to review than re-reading the engine's release notes.

Usage:
    python scripts/snapshot_corpus.py [--check]

``--check`` exits non-zero if the snapshot is out of date, for use in CI.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from ritarinn.services.correction.base import CorrectionRequest  # noqa: E402
from ritarinn.services.correction.greynir import GreynirCorrectEngine  # noqa: E402

CASES_PATH = REPO_ROOT / "corpus" / "cases.json"
OUTPUT_PATH = REPO_ROOT / "corpus" / "observed.json"


def build_snapshot() -> dict:
    engine = GreynirCorrectEngine()
    status = engine.status()

    cases = json.loads(CASES_PATH.read_text(encoding="utf-8"))["cases"]
    observed = []
    for case in cases:
        outcome = engine.analyze(CorrectionRequest(text=case["text"]))
        observed.append(
            {
                "id": case["id"],
                "register": case["register"],
                "issues": [
                    {
                        "code": issue.code,
                        "category": issue.category,
                        "family": issue.family,
                        "scope": issue.scope,
                        "severity": issue.severity,
                        "startChar": issue.start_char,
                        "endChar": issue.end_char,
                        "original": issue.original,
                        "replacement": issue.replacement,
                        "title": issue.title,
                    }
                    for issue in outcome.issues
                ],
            }
        )

    return {
        "note": (
            "Generated by scripts/snapshot_corpus.py. A review aid, not a test "
            "fixture — GreynirCorrect's behaviour is the source of truth."
        ),
        "engine": status.name,
        "engineVersion": status.version,
        "cases": observed,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if the snapshot is stale"
    )
    args = parser.parse_args()

    snapshot = build_snapshot()
    serialised = json.dumps(snapshot, ensure_ascii=False, indent=2) + "\n"

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run without --check", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != serialised:
            print(f"{OUTPUT_PATH} is out of date; run without --check", file=sys.stderr)
            return 1
        print("snapshot is up to date")
        return 0

    OUTPUT_PATH.write_text(serialised, encoding="utf-8")
    total = sum(len(case["issues"]) for case in snapshot["cases"])
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}: {len(snapshot['cases'])} cases, {total} issues")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
